sudo: required
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.5-dev' # 3.5 development branch
  - '3.6-dev' # 3.6 development branch

# command to install dependencies
install:
  - sudo start-docker-daemon
  - echo "---> Check Docker version" && docker version
  - echo "---> Installing CI utils" && pip install docker-compose
  - if [[ $TRAVIS_PYTHON_VERSION == 2.* ]]; then pip install -r client/requirements.txt && pip install -r client/requirements-dev.txt && pip install -r server/requirements.txt fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.* ]]; then pip3 install -r client/requirements.txt && pip3 install -r client/requirements-dev.txt && pip3 install -r server/requirements.txt fi
  - git clone https://github.com/sstephenson/bats.git && cd bats && ./install.sh /usr/local

# command to run tests
script: 
  - pylint client/cassh -d redefined-builtin -d useless-object-inheritance || travis_terminate 1
  - pylint server/server -d redefined-builtin -d useless-object-inheritance || travis_terminate 1
  - tests/tests.sh

